site_name: Documentación Parcial Final N-Capas
theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Inicio: index.md
  - Desarrollo y Roles: desarrollo.md
  - Despliegue y Pruebas: despliegue.md
